apiVersion: v1
kind: ConfigMap
metadata:
  name: smart-bet-config
  labels:
    app: smart-bet-backend
    environment: prod
data:
  # Spring Profile
  spring-profile: "prod"
  
  # Database configuration (DigitalOcean Managed Database)
  # IMPORTANTE: Atualize estes valores com seu banco de dados
  db-host: "private-smartbet-postgres-dev-do-user-32074130-0.f.db.ondigitalocean.com"
  db-port: "25060"
  db-name: "smartbet_dev"
  
  # Logging
  log-level: "WARN"
