apiVersion: v1
kind: ConfigMap
metadata:
  name: smart-bet-config
  labels:
    app: smart-bet-backend
    environment: dev
data:
  # Spring Profile
  spring-profile: "dev"
  
  # Database configuration (DigitalOcean Managed Database - VPC Network)
  db-host: "private-smartbet-postgres-dev-do-user-32074130-0.f.db.ondigitalocean.com"
  db-port: "25060"
  db-name: "defaultdb"
  db-sslmode: "require"
  
  # Logging
  log-level: "DEBUG"
