apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smartbet-dev

resources:
  - ../../base
  - configmap.yaml
  - secret.yaml
  - namespace.yaml

commonLabels:
  environment: dev

patches:
  # Recursos reduzidos para ambiente de desenvolvimento
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "100m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "250m"
    target:
      kind: Deployment
      name: smart-bet-backend

  # Dom√≠nio do ambiente de desenvolvimento
  - patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: api-dev.smartbet.example.com
      - op: replace
        path: /spec/rules/0/host
        value: api-dev.smartbet.example.com
    target:
      kind: Ingress
      name: smart-bet-ingress

images:
  - name: ghcr.io/ednilsoncampos/smart-bet-manager-kotlin
    newTag: dev
