apiVersion: v1
kind: ConfigMap
metadata:
  name: smart-bet-config
  labels:
    app: smart-bet-backend
    environment: staging
data:
  # Spring Profile
  spring-profile: "staging"
  
  # Database configuration (DigitalOcean Managed Database - VPC Network) smartbet.api.br
  # IMPORTANTE: Atualize estes valores com seu banco de dados de staging
  db-host: "smartbet-postgres-dev-do-user-32074130-0.f.db.ondigitalocean.com"
  db-port: "25060"
  db-name: "smartbet_stg"
  db-sslmode: "require"
  
  # Logging
  log-level: "INFO"
